<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice rule</name>
  <uuid>bef1d370-0945-4199-ac80-9d415dac2d1a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	name is defined 
then
	set decision to "Hello " + name ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
